### PR TITLE
Make a start at adding non-generic serialize overloads

### PR DESCRIPTION
**Pull request by trippwill**

### CODE REVIEW

**Comment by trippwill** [comment]
@AArnott - tried making a start on adding non-generic, Type accepting overloads.

**Comment by AArnott** [comment]
Oh, I just noticed this after creating #181. 
I see you added more overloads than I did. Which ones would you directly use? We already have a _lot_ of serialize/deserialize overloads so I'm looking to keep this hopefully rare case cornered off to just a few overloads even if they're a little harder to use.

**Comment by trippwill** [comment]
Looks like the primary synchronous overloads which take a shape provider and a Type instance would be the ones I would use for vs-streamjsonrpc.

I'll close this PR.

**Comment by AArnott** [comment]
> take a shape provider and a Type instance

Would taking an `ITypeShape` instead (which encompasses both the Type and the shape provider) suffice?

**Pull request closed without merging**
